site_name: algo
nav: 
    - 刷题记录:
        - 刷题记录\dp.md
        - 刷题记录\数学.md
        - 刷题记录\数据结构.md
    - 概论:
        - 概论/自由探索.md
        - 概论/校赛.md
        - 概论/1.常见算法.md
        - 概论/2.搜索.md
        - 概论/3.杂项.md
        - 概论/4.数学.md
        - 概论/5.dp.md
        - 概论/6.数据结构.md
        - 概论/7.图论.md
        - 概论/8.计算几何.md
        - 概论/9.字符串.md
    - 理论:
        - 理论\1.常见算法.md
        - 理论\2.搜索.md
        - 理论\3.杂项.md
        - 理论\4.数学.md
        - 理论\5.dp.md
        - 理论\6.数据结构.md
        - 理论\7.图论.md
        - 理论\8.计算几何.md
        - 理论\9.字符串.md
        - 理论\数论.md
    - 特训:
        - 特训/vp.md
        - 特训/题目模型.md
        - 特训/题目.md
        - 特训/策略.md
        - 特训/算法竞赛.md
        - 特训/cf.md
        - 特训/dp.md
    - 刷题:
        - 刷题/1.数论.md
        - 刷题/2.树状数组.md
        - 刷题/3.并查集.md
        - 刷题/4.矩阵.md
        - 刷题/5.数论.md
        - 刷题/7.二分&尺取.md
        - 刷题/8.容斥&莫比乌斯反演.md
        - 刷题/9.单调栈&单调队列.md
        - 刷题/10.kmp.md
        - 刷题/11.区间dp.md
        - 刷题/区间dp.md
        - 刷题/双指针.md
        - 刷题/思维.md
        - 刷题/数论.md
        - 刷题/最短路.md
        - 刷题/最短路1.md
        - 刷题/树形dp.md
        - 刷题/线性dp.md
        - 刷题/背包dp.md
extra_css:
    - res/extra.css
extra_javascript:
    - res/extra.js

    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 - 2023 travis

# repo_url: @
# repo_name: @

theme:
    name: material
    # custom_dir: overrides

    palette:
        - media: "(prefers-color-scheme)"
          primary: red
          accent: red
          toggle:
            icon: material/brightness-auto
            name: 切换到暗模式
        - media: "(prefers-color-scheme: light)"
          primary: green
          accent: green
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: 切换到默认模式
        - media: "(prefers-color-scheme: dark)"
          primary: blue
          accent: blue
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: 切换到亮模式

    font:
        text: Roboto
        code: Roboto Mono

    language: en
    direction: ltr

    logo: https://static.javatpoint.com/perl/images/perl-home.png
    favicon: https://static.javatpoint.com/perl/images/perl-home.png
    icon:
        logo: octicons/heart-fill-24

        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye


        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left




    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        # - navigation.expand
        - navigation.prune
        - navigation.indexes
        - toc.follow
        # - toc.integrate
        - navigation.top

        - search.suggest
        - search.highlight
        - search.share

        - header.autohide

        - navigation.footer

        - content.action.edit
        - content.action.view

        - content.code.copy
        - content.code.annotate

        - content.tooltips


extra:
    alternate:
        - name: vjudge
          link: https://vjudge.csgrandeur.cn/article/187
        - name: oiwiki
          link: https://oi-wiki.org/
          lang: zh
        - name: cp-algorithms
          link: https://cp-algorithms.com/index.html
          lang: zh
        - name: nowcoder
          link: https://ac.nowcoder.com/acm/skill/acm
          lang: zh
        - name: cppreference
          link: https://zh.cppreference.com/w/cpp
          lang: zh

    homepage: /

    #consent:
    #    title: cookie
    #    description:    >-
    #        sdd
    #    cookies:
    #        analytics:
    #            github


    social:
        - icon: fontawesome/brands/github
          link: 链接url地址
          name: 标识名
        - icon: fontawesome/brands/docker
          link: 链接url地址
          name: 标识名
    generator: false


plugins:
    - search:
        lang:
            - en
            - ja
        # '[\s\-,:!=\[\]]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
        separator: '[\s\-\.]+'
        jieba_dict: res/dict.txt
        jieba_dict_user: res/user_dict.txt
    - search:
        lang:
            - en
        jieba_dict: dict/dict.txt
        separator: '[\s\-\.]+'
    # - typeset

    - glightbox

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    - attr_list
    - md_in_html
    - pymdownx.superfences

    - attr_list

    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    #- pymdownx.tabbed:
    #    slugify: !!python/object/apply:pymdownx.slugs.slugify
    #        kwds:
    #            case: lower

    # - content.tabs.link


    - tables
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes

    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg


    - attr_list
    - md_in_html

    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

    - pymdownx.arithmatex:
        generic: true

    - abbr
    - attr_list
    - pymdownx.snippets
    - pymdownx.snippets:
        auto_append:
            - includes/abbr.md

